### ISSUE TITLE
Not working on High Sierra(10.13.5 )

### ISSUE THREAD

**Issue by ShenZehong** [nmecad/markdown-img-paste#12]

**Comment by EasterFan** [comment]
Me too !  I love this atom plugin deadly! It works perfectly in ubuntu 16.04 , but in mac high sierra 10.13.5, "ctrl + v " nor "commd + v" doesn't work 😭 , i miss it 😭

**Comment by ShenZehong** [comment]
Emmmm, actually, I am using typora instead
