### ISSUE TITLE
Can't ctrl+c/ctrl+v to copy a image into markdown file?

### ISSUE THREAD

**Issue by hitzhangjie** [nmecad/markdown-img-paste#16]
Hi, I can't ctrl+c/ctrl+v to copy a image into markdown file, but drag and drop works. I don't know why it does like this. I also changed the shortcut from 'ctrl-v' to 'ctrl-alt-v' or other not conflict ones, it neither works.

**Comment by zmbcen** [comment]
hello,i alco have encouterd this problem,could you tell me how did you solved it ?

**Comment by zmbcen** [comment]
i have install it successfuly,the follwing is my setting
![image](https://user-images.githubusercontent.com/36689942/55604701-af122b00-57a3-11e9-8610-85da0a7cc06c.png)
when i click ctrl+v of ctrl+shirft+v,there is no action happen
